/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void textarea1_change1(GTextArea source, GEvent event) { //_CODE_:textarea1:971488:
  println("textarea1 - GTextArea >> GEvent." + event + " @ " + millis());
} //_CODE_:textarea1:971488:

public void button1_click1(GButton source, GEvent event) { //_CODE_:translateButton:745418:
  println("translateButton - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:translateButton:745418:

public void button2_click1(GButton source, GEvent event) { //_CODE_:Rotation:688787:
  println("Rotation - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:Rotation:688787:

public void textfield1_change1(GTextField source, GEvent event) { //_CODE_:translateX:662246:
  println("translateX - GTextField >> GEvent." + event + " @ " + millis());
} //_CODE_:translateX:662246:

public void textfield2_change1(GTextField source, GEvent event) { //_CODE_:translateY:794524:
  println("translateY - GTextField >> GEvent." + event + " @ " + millis());
} //_CODE_:translateY:794524:

public void textfield1_change2(GTextField source, GEvent event) { //_CODE_:rotationY:453161:
  println("rotationY - GTextField >> GEvent." + event + " @ " + millis());
} //_CODE_:rotationY:453161:

public void textfield2_change2(GTextField source, GEvent event) { //_CODE_:rotationX:614159:
  println("rotationX - GTextField >> GEvent." + event + " @ " + millis());
} //_CODE_:rotationX:614159:

public void button1_click2(GButton source, GEvent event) { //_CODE_:scaling:779376:
  println("scaling - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:scaling:779376:

public void textfield1_change3(GTextField source, GEvent event) { //_CODE_:scalingX:703502:
  println("scalingX - GTextField >> GEvent." + event + " @ " + millis());
} //_CODE_:scalingX:703502:

public void textfield2_change3(GTextField source, GEvent event) { //_CODE_:scalingY:955386:
  println("scalingY - GTextField >> GEvent." + event + " @ " + millis());
} //_CODE_:scalingY:955386:

public void button1_click3(GButton source, GEvent event) { //_CODE_:Shear:248649:
  println("Shear - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:Shear:248649:

public void textfield1_change4(GTextField source, GEvent event) { //_CODE_:sheaRX:925329:
  println("sheaRX - GTextField >> GEvent." + event + " @ " + millis());
} //_CODE_:sheaRX:925329:

public void textfield2_change4(GTextField source, GEvent event) { //_CODE_:sheaRY:620668:
  println("sheaRY - GTextField >> GEvent." + event + " @ " + millis());
} //_CODE_:sheaRY:620668:

public void button1_click4(GButton source, GEvent event) { //_CODE_:refleksi:608289:
  println("refleksi - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:refleksi:608289:

public void textfield3_change1(GTextField source, GEvent event) { //_CODE_:reflectX:340674:
  println("reflectX - GTextField >> GEvent." + event + " @ " + millis());
} //_CODE_:reflectX:340674:

public void textfield4_change1(GTextField source, GEvent event) { //_CODE_:reflectY:737224:
  println("reflectY - GTextField >> GEvent." + event + " @ " + millis());
} //_CODE_:reflectY:737224:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setCursor(ARROW);
  surface.setTitle("Sketch Window");
  textarea1 = new GTextArea(this, 0, 0, 900, 900, G4P.SCROLLBARS_NONE);
  textarea1.setLocalColorScheme(GCScheme.SCHEME_15);
  textarea1.setOpaque(true);
  textarea1.addEventHandler(this, "textarea1_change1");
  translateButton = new GButton(this, 920, 20, 170, 30);
  translateButton.setText("TRANSLASI");
  translateButton.setTextBold();
  translateButton.addEventHandler(this, "button1_click1");
  Rotation = new GButton(this, 920, 110, 170, 30);
  Rotation.setText("ROTASI");
  Rotation.setTextBold();
  Rotation.addEventHandler(this, "button2_click1");
  translateX = new GTextField(this, 920, 60, 80, 30, G4P.SCROLLBARS_NONE);
  translateX.setOpaque(true);
  translateX.addEventHandler(this, "textfield1_change1");
  translateY = new GTextField(this, 1010, 60, 80, 30, G4P.SCROLLBARS_NONE);
  translateY.setOpaque(true);
  translateY.addEventHandler(this, "textfield2_change1");
  rotationY = new GTextField(this, 1010, 150, 80, 30, G4P.SCROLLBARS_NONE);
  rotationY.setOpaque(true);
  rotationY.addEventHandler(this, "textfield1_change2");
  rotationX = new GTextField(this, 920, 150, 80, 30, G4P.SCROLLBARS_NONE);
  rotationX.setOpaque(true);
  rotationX.addEventHandler(this, "textfield2_change2");
  scaling = new GButton(this, 920, 200, 170, 30);
  scaling.setText("SKALA");
  scaling.setTextBold();
  scaling.addEventHandler(this, "button1_click2");
  scalingX = new GTextField(this, 920, 240, 80, 30, G4P.SCROLLBARS_NONE);
  scalingX.setOpaque(true);
  scalingX.addEventHandler(this, "textfield1_change3");
  scalingY = new GTextField(this, 1010, 240, 80, 30, G4P.SCROLLBARS_NONE);
  scalingY.setOpaque(true);
  scalingY.addEventHandler(this, "textfield2_change3");
  Shear = new GButton(this, 920, 290, 170, 30);
  Shear.setText("SHEAR");
  Shear.setTextBold();
  Shear.addEventHandler(this, "button1_click3");
  sheaRX = new GTextField(this, 920, 330, 80, 30, G4P.SCROLLBARS_NONE);
  sheaRX.setOpaque(true);
  sheaRX.addEventHandler(this, "textfield1_change4");
  sheaRY = new GTextField(this, 1010, 330, 80, 30, G4P.SCROLLBARS_NONE);
  sheaRY.setOpaque(true);
  sheaRY.addEventHandler(this, "textfield2_change4");
  refleksi = new GButton(this, 920, 380, 170, 30);
  refleksi.setText("REFLEKSI");
  refleksi.setTextBold();
  refleksi.addEventHandler(this, "button1_click4");
  reflectX = new GTextField(this, 920, 420, 80, 30, G4P.SCROLLBARS_NONE);
  reflectX.setOpaque(true);
  reflectX.addEventHandler(this, "textfield3_change1");
  reflectY = new GTextField(this, 1010, 420, 80, 30, G4P.SCROLLBARS_NONE);
  reflectY.setOpaque(true);
  reflectY.addEventHandler(this, "textfield4_change1");
}

// Variable declarations 
// autogenerated do not edit
GTextArea textarea1; 
GButton translateButton; 
GButton Rotation; 
GTextField translateX; 
GTextField translateY; 
GTextField rotationY; 
GTextField rotationX; 
GButton scaling; 
GTextField scalingX; 
GTextField scalingY; 
GButton Shear; 
GTextField sheaRX; 
GTextField sheaRY; 
GButton refleksi; 
GTextField reflectX; 
GTextField reflectY; 
