/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void translasi(GButton source, GEvent event) { //_CODE_:translateButton:745418:
String x1 = translateX.getText();
int x = Integer.parseInt(x1);
String y1 = translateY.getText();
int y = Integer.parseInt(y1);
translate(x,y);
} //_CODE_:translateButton:745418:

public void rotasi(GButton source, GEvent event) { //_CODE_:Rotation:688787:
String x1 = rotationX.getText();
int x = Integer.parseInt(x1);
String y1 = rotationY.getText();
int y = Integer.parseInt(y1);
rotateX(x);
rotateY(y);
} //_CODE_:Rotation:688787:

public void translasiX(GTextField source, GEvent event) { //_CODE_:translateX:662246:

} //_CODE_:translateX:662246:

public void translasiY(GTextField source, GEvent event) { //_CODE_:translateY:794524:
  println("translateY - GTextField >> GEvent." + event + " @ " + millis());
} //_CODE_:translateY:794524:

public void rotasiY(GTextField source, GEvent event) { //_CODE_:rotationY:453161:
  println("rotationY - GTextField >> GEvent." + event + " @ " + millis());
} //_CODE_:rotationY:453161:

public void rotasiX(GTextField source, GEvent event) { //_CODE_:rotationX:614159:
  println("rotationX - GTextField >> GEvent." + event + " @ " + millis());
} //_CODE_:rotationX:614159:

public void skala(GButton source, GEvent event) { //_CODE_:scaling:779376:
String x1 = scalingX.getText();
int x = Integer.parseInt(x1);
String y1 = scalingY.getText();
int y = Integer.parseInt(y1);
scale(x,y);
} //_CODE_:scaling:779376:

public void skalaX(GTextField source, GEvent event) { //_CODE_:scalingX:703502:
  println("scalingX - GTextField >> GEvent." + event + " @ " + millis());
} //_CODE_:scalingX:703502:

public void skalaY(GTextField source, GEvent event) { //_CODE_:scalingY:955386:
  println("scalingY - GTextField >> GEvent." + event + " @ " + millis());
} //_CODE_:scalingY:955386:

public void shear(GButton source, GEvent event) { //_CODE_:Shear:248649:
String x1 = sheaRX.getText();
int x = Integer.parseInt(x1);
String y1 = sheaRY.getText();
int y = Integer.parseInt(y1);
shearX(x);
shearY(y);
} //_CODE_:Shear:248649:

public void shearingX(GTextField source, GEvent event) { //_CODE_:sheaRX:925329:
  println("sheaRX - GTextField >> GEvent." + event + " @ " + millis());
} //_CODE_:sheaRX:925329:

public void shearingY(GTextField source, GEvent event) { //_CODE_:sheaRY:620668:
  println("sheaRY - GTextField >> GEvent." + event + " @ " + millis());
} //_CODE_:sheaRY:620668:

public void reflect(GButton source, GEvent event) { //_CODE_:refleksi:608289:
String x1 = reflectX.getText();
int x = Integer.parseInt(x1);
String y1 = reflectY.getText();
int y = Integer.parseInt(y1);
} //_CODE_:refleksi:608289:

public void refleksiX(GTextField source, GEvent event) { //_CODE_:reflectX:340674:
  println("reflectX - GTextField >> GEvent." + event + " @ " + millis());
} //_CODE_:reflectX:340674:

public void reflaksiY(GTextField source, GEvent event) { //_CODE_:reflectY:737224:
  println("reflectY - GTextField >> GEvent." + event + " @ " + millis());
} //_CODE_:reflectY:737224:

public void textarea1_change1(GTextArea source, GEvent event) { //_CODE_:textarea1:466787:
  println("textarea1 - GTextArea >> GEvent." + event + " @ " + millis());
} //_CODE_:textarea1:466787:

public void translation(GButton source, GEvent event) { //_CODE_:translat:715763:
  println("translat - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:translat:715763:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setCursor(ARROW);
  surface.setTitle("Sketch Window");
  translateButton = new GButton(this, 1513, 20, 170, 30);
  translateButton.setText("TRANSLASI");
  translateButton.setTextBold();
  translateButton.addEventHandler(this, "translasi");
  Rotation = new GButton(this, 920, 110, 170, 30);
  Rotation.setText("ROTASI");
  Rotation.setTextBold();
  Rotation.addEventHandler(this, "rotasi");
  translateX = new GTextField(this, 920, 60, 80, 30, G4P.SCROLLBARS_NONE);
  translateX.setText("Koordinat X");
  translateX.setOpaque(true);
  translateX.addEventHandler(this, "translasiX");
  translateY = new GTextField(this, 1010, 60, 80, 30, G4P.SCROLLBARS_NONE);
  translateY.setText("Koordinat Y");
  translateY.setOpaque(true);
  translateY.addEventHandler(this, "translasiY");
  rotationY = new GTextField(this, 1010, 150, 80, 30, G4P.SCROLLBARS_NONE);
  rotationY.setOpaque(true);
  rotationY.addEventHandler(this, "rotasiY");
  rotationX = new GTextField(this, 920, 150, 80, 30, G4P.SCROLLBARS_NONE);
  rotationX.setOpaque(true);
  rotationX.addEventHandler(this, "rotasiX");
  scaling = new GButton(this, 920, 200, 170, 30);
  scaling.setText("SKALA");
  scaling.setTextBold();
  scaling.addEventHandler(this, "skala");
  scalingX = new GTextField(this, 920, 240, 80, 30, G4P.SCROLLBARS_NONE);
  scalingX.setOpaque(true);
  scalingX.addEventHandler(this, "skalaX");
  scalingY = new GTextField(this, 1010, 240, 80, 30, G4P.SCROLLBARS_NONE);
  scalingY.setOpaque(true);
  scalingY.addEventHandler(this, "skalaY");
  Shear = new GButton(this, 920, 290, 170, 30);
  Shear.setText("SHEAR");
  Shear.setTextBold();
  Shear.addEventHandler(this, "shear");
  sheaRX = new GTextField(this, 920, 330, 80, 30, G4P.SCROLLBARS_NONE);
  sheaRX.setOpaque(true);
  sheaRX.addEventHandler(this, "shearingX");
  sheaRY = new GTextField(this, 1010, 330, 80, 30, G4P.SCROLLBARS_NONE);
  sheaRY.setOpaque(true);
  sheaRY.addEventHandler(this, "shearingY");
  refleksi = new GButton(this, 920, 380, 170, 30);
  refleksi.setText("REFLEKSI");
  refleksi.setTextBold();
  refleksi.addEventHandler(this, "reflect");
  reflectX = new GTextField(this, 920, 420, 80, 30, G4P.SCROLLBARS_NONE);
  reflectX.setOpaque(true);
  reflectX.addEventHandler(this, "refleksiX");
  reflectY = new GTextField(this, 1010, 420, 80, 30, G4P.SCROLLBARS_NONE);
  reflectY.setOpaque(true);
  reflectY.addEventHandler(this, "reflaksiY");
  textarea1 = new GTextArea(this, 0, 0, 900, 900, G4P.SCROLLBARS_NONE);
  textarea1.setLocalColorScheme(GCScheme.SCHEME_8);
  textarea1.setOpaque(true);
  textarea1.addEventHandler(this, "textarea1_change1");
  translat = new GButton(this, 920, 20, 170, 30);
  translat.setText("TRANSLASI");
  translat.setTextBold();
  translat.addEventHandler(this, "translation");
}

// Variable declarations 
// autogenerated do not edit
GButton translateButton; 
GButton Rotation; 
GTextField translateX; 
GTextField translateY; 
GTextField rotationY; 
GTextField rotationX; 
GButton scaling; 
GTextField scalingX; 
GTextField scalingY; 
GButton Shear; 
GTextField sheaRX; 
GTextField sheaRY; 
GButton refleksi; 
GTextField reflectX; 
GTextField reflectY; 
GTextArea textarea1; 
GButton translat; 
